### ISSUE TITLE
Possibility of optionalizing Security Group?

### ISSUE THREAD

**Issue by Prophecy67** [terra-mod/terraform-aws-ecs-service#3]
The default egress for the service with a 0.0.0.0/0 is particularly open. Is there a possibility to adjust this for security sake?

https://github.com/terra-mod/terraform-aws-ecs-service/blob/03dccfa74c6f0359eef06c673c615e271bb9f698/main.tf#L33

**Comment by kmfk** [comment]
Yeah, that's fair. I can add in an input var to avoid creating that rule. Will try and get to that in the next day or two.

**Comment by Prophecy67** [comment]
This functionality had already been implemented by you @kmfk , for which thanks a ton!

**Comment by kmfk** [comment]
👍
