### ISSUE TITLE
Optionalizing platform_version

### ISSUE THREAD

**Issue by Prophecy67** [terra-mod/terraform-aws-ecs-service#4]
Since ECS is upgrading to version 1.4.0, I thought it a great time to also put in a pull-request for setting the platform_version var. Both for others' backwards compatibility as much as providing the possibility to do forward-testing, by setting the version to 1.4.0 already.

We can modify the variables.tf and add in the default of LATEST, which it already is. The module itself however, can then also support setting different versions.

**Comment by kmfk** [comment]
Merged #5 - thanks again!
